services:
  client_0:
    build:
      context: ./src/
      dockerfile: client/Dockerfile
    container_name: client_0
    depends_on:
    - distributor_0
    environment:
    - INPUT_FILE=/datasets/input_0.csv
    - OUTPUT_FILE_PREFIX=/output/0/output_
    - PYTHONUNBUFFERED=1
    - SERVER_HOST=gateway
    - SERVER_PORT=5678
    volumes:
    - ./datasets:/datasets
    - ./output:/output
  gateway:
    build:
      context: ./src/
      dockerfile: gateway/Dockerfile
    container_name: gateway
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
    - INPUT_QUEUE=results_queue
    - MOM_HOST=rabbitmq
    - OUTPUT_QUEUE=input_queue
    - PYTHONUNBUFFERED=1
    - SERVER_HOST=gateway
    - SERVER_PORT=5678
    - DISTRIBUTOR_AMOUNT=1
    - DISTRIBUTOR_PREFIX=distributor
  rabbitmq:
    build:
      context: ./src/rabbitmq
      dockerfile: Dockerfile
    container_name: rabbitmq
    environment:
    - RABBITMQ_LOG_LEVELS=error
    healthcheck:
      interval: 5s
      retries: 10
      start_period: 50s
      test: rabbitmq-diagnostics check_port_connectivity
      timeout: 3s
    ports:
    - 5672:5672
    - 15672:15672
  distributor_0:
    build:
      context: ./src/
      dockerfile: distributor/Dockerfile
    container_name: distributor_0
    depends_on:
    - q1_join
    - bank_mapper_0
    environment:
    - ID=0
    - INPUT_QUEUE=input_queue
    - Q1_QUEUE=q1_queue
    - Q2_QUEUE=q2_queue
    - Q3_QUEUE=q3_queue
    - Q4_QUEUE=q4_queue
    - Q5_QUEUE=q5_queue
    - MOM_HOST=rabbitmq
    - PYTHONUNBUFFERED=1

  # QUERY 1
  q1_join:
    build:
      context: ./src/
      dockerfile: q1_join/Dockerfile
    container_name: q1_join
    depends_on:
    - gateway
    environment:
    - INPUT_QUEUE=q1_queue
    - OUTPUT_QUEUE=results_queue
    - MOM_HOST=rabbitmq
    - PYTHONUNBUFFERED=1

  # QUERY 2
  bank_mapper_0:
    build:
      context: ./src/
      dockerfile: bank_mapper/Dockerfile
    container_name: bank_mapper_0
    depends_on:
    - bank_max_0
    environment:
    - ID=0
    - INPUT_QUEUE=q2_queue
    - MOM_HOST=rabbitmq
    - PYTHONUNBUFFERED=1
    - BANK_MAX_AMOUNT=1
    - BANK_MAX_PREFIX=bank_max
  bank_max_0:
    build:
      context: ./src/
      dockerfile: bank_max/Dockerfile
    container_name: bank_max_0
    depends_on:
    - q2_join
    environment:
    - ID=0
    - OUTPUT_QUEUE=q2_join_queue
    - MOM_HOST=rabbitmq
    - PYTHONUNBUFFERED=1
    - BANK_MAX_AMOUNT=1
    - BANK_MAX_PREFIX=bank_max
  q2_join:
    build:
      context: ./src/
      dockerfile: q2_join/Dockerfile
    container_name: q2_join
    depends_on:
    - gateway
    environment:
    - ID=0
    - INPUT_QUEUE=q2_join_queue
    - OUTPUT_QUEUE=results_queue
    - MOM_HOST=rabbitmq
    - PYTHONUNBUFFERED=1
    - BANK_MAX_AMOUNT=1

  # QUERY 3
  mapper_and_distributor_0:
    build:
      context: ./src/
      dockerfile: mapper_and_distributor/Dockerfile
    container_name: mapper_and_distributor_0
    depends_on:
    - payment_format_avg_0
    - payment_format_avg_1
    - payment_format_avg_2
    environment:
    - ID=0
    - INPUT_QUEUE=q3_queue
    - MOM_HOST=rabbitmq
    - PYTHONUNBUFFERED=1
    - MAPPER_AND_DISTRIBUTOR_AMOUNT=3
    - MAPPER_AND_DISTRIBUTOR_PREFIX=mapper_and_distributor
    - PAYMENT_FORMAT_AVG_AMOUNT=3
    - PAYMENT_FORMAT_AVG_PREFIX=payment_format_avg
    - AMOUNT_FILTER_AMOUNT=3
    - AMOUNT_FILTER_PREFIX=amount_filter
  mapper_and_distributor_1:
    build:
      context: ./src/
      dockerfile: mapper_and_distributor/Dockerfile
    container_name: mapper_and_distributor_1
    depends_on:
    - payment_format_avg_0
    - payment_format_avg_1
    - payment_format_avg_2
    environment:
    - ID=1
    - INPUT_QUEUE=q3_queue
    - MOM_HOST=rabbitmq
    - PYTHONUNBUFFERED=1
    - MAPPER_AND_DISTRIBUTOR_AMOUNT=3
    - MAPPER_AND_DISTRIBUTOR_PREFIX=mapper_and_distributor
    - PAYMENT_FORMAT_AVG_AMOUNT=3
    - PAYMENT_FORMAT_AVG_PREFIX=payment_format_avg
    - AMOUNT_FILTER_AMOUNT=3
    - AMOUNT_FILTER_PREFIX=amount_filter
  mapper_and_distributor_2:
    build:
      context: ./src/
      dockerfile: mapper_and_distributor/Dockerfile
    container_name: mapper_and_distributor_2
    depends_on:
    - payment_format_avg_0
    - payment_format_avg_1
    - payment_format_avg_2
    environment:
    - ID=2
    - INPUT_QUEUE=q3_queue
    - MOM_HOST=rabbitmq
    - PYTHONUNBUFFERED=1
    - MAPPER_AND_DISTRIBUTOR_AMOUNT=3
    - MAPPER_AND_DISTRIBUTOR_PREFIX=mapper_and_distributor
    - PAYMENT_FORMAT_AVG_AMOUNT=3
    - PAYMENT_FORMAT_AVG_PREFIX=payment_format_avg
    - AMOUNT_FILTER_AMOUNT=3
    - AMOUNT_FILTER_PREFIX=amount_filter
  payment_format_avg_0:
    build:
      context: ./src/
      dockerfile: payment_format_avg/Dockerfile
    container_name: payment_format_avg_0
    depends_on:
    - amount_filter_0
    - amount_filter_1
    - amount_filter_2
    environment:
    - ID=0
    - MOM_HOST=rabbitmq
    - PYTHONUNBUFFERED=1
    - PAYMENT_FORMAT_AVG_AMOUNT=3
    - PAYMENT_FORMAT_AVG_PREFIX=payment_format_avg
    - AMOUNT_FILTER_AMOUNT=3
    - AMOUNT_FILTER_PREFIX=amount_filter
    - MAPPER_AND_DISTRIBUTOR_AMOUNT=3
  payment_format_avg_1:
    build:
      context: ./src/
      dockerfile: payment_format_avg/Dockerfile
    container_name: payment_format_avg_1
    depends_on:
    - amount_filter_0
    - amount_filter_1
    - amount_filter_2
    environment:
    - ID=1
    - MOM_HOST=rabbitmq
    - PYTHONUNBUFFERED=1
    - PAYMENT_FORMAT_AVG_AMOUNT=3
    - PAYMENT_FORMAT_AVG_PREFIX=payment_format_avg
    - AMOUNT_FILTER_AMOUNT=3
    - AMOUNT_FILTER_PREFIX=amount_filter
    - MAPPER_AND_DISTRIBUTOR_AMOUNT=3
  payment_format_avg_2:
    build:
      context: ./src/
      dockerfile: payment_format_avg/Dockerfile
    container_name: payment_format_avg_2
    depends_on:
    - amount_filter_0
    - amount_filter_1
    - amount_filter_2
    environment:
    - ID=2
    - MOM_HOST=rabbitmq
    - PYTHONUNBUFFERED=1
    - PAYMENT_FORMAT_AVG_AMOUNT=3
    - PAYMENT_FORMAT_AVG_PREFIX=payment_format_avg
    - AMOUNT_FILTER_AMOUNT=3
    - AMOUNT_FILTER_PREFIX=amount_filter
    - MAPPER_AND_DISTRIBUTOR_AMOUNT=3
  amount_filter_0:
    build:
      context: ./src/
      dockerfile: amount_filter/Dockerfile
    container_name: amount_filter_0
    depends_on:
    - q3_join
    environment:
    - ID=0
    - OUTPUT_QUEUE=amount_filter_queue
    - MOM_HOST=rabbitmq
    - PYTHONUNBUFFERED=1
    - AMOUNT_FILTER_AMOUNT=3
    - AMOUNT_FILTER_PREFIX=amount_filter
    - PAYMENT_FORMAT_AVG_AMOUNT=3
  amount_filter_1:
    build:
      context: ./src/
      dockerfile: amount_filter/Dockerfile
    container_name: amount_filter_1
    depends_on:
    - q3_join
    environment:
    - ID=1
    - OUTPUT_QUEUE=amount_filter_queue
    - MOM_HOST=rabbitmq
    - PYTHONUNBUFFERED=1
    - AMOUNT_FILTER_AMOUNT=3
    - AMOUNT_FILTER_PREFIX=amount_filter
    - PAYMENT_FORMAT_AVG_AMOUNT=3
  amount_filter_2:
    build:
      context: ./src/
      dockerfile: amount_filter/Dockerfile
    container_name: amount_filter_2
    depends_on:
    - q3_join
    environment:
    - ID=2
    - OUTPUT_QUEUE=amount_filter_queue
    - MOM_HOST=rabbitmq
    - PYTHONUNBUFFERED=1
    - AMOUNT_FILTER_AMOUNT=3
    - AMOUNT_FILTER_PREFIX=amount_filter
    - PAYMENT_FORMAT_AVG_AMOUNT=3
  q3_join:
    build:
      context: ./src/
      dockerfile: q3_join/Dockerfile
    container_name: q3_join
    depends_on: 
    - gateway
    environment:
    - INPUT_QUEUE=amount_filter_queue
    - OUTPUT_QUEUE=results_queue
    - MOM_HOST=rabbitmq
    - PYTHONUNBUFFERED=1
    - AMOUNT_FILTER_AMOUNT=3

  # QUERY 4

  # QUERY 5

