services:
  client_0:
    build:
      context: ./
      dockerfile: client/Dockerfile
    container_name: client_0
    depends_on:
    - filter_0
    environment:
    - INPUT_FILE=/datasets/input_0.csv
    - OUTPUT_FILE=/output/output_0.csv
    - PYTHONUNBUFFERED=1
    - SERVER_HOST=gateway
    - SERVER_PORT=5678
    volumes:
    - ../datasets:/datasets
    - ../output:/output
  gateway:
    build:
      context: ./
      dockerfile: gateway/Dockerfile
    container_name: gateway
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
    - INPUT_QUEUE=results_queue
    - MOM_HOST=rabbitmq
    - OUTPUT_QUEUE=input_queue
    - PYTHONUNBUFFERED=1
    - SERVER_HOST=gateway
    - SERVER_PORT=5678
  rabbitmq:
    build:
      context: ./rabbitmq
      dockerfile: Dockerfile
    container_name: rabbitmq
    environment:
    - RABBITMQ_LOG_LEVELS=error
    healthcheck:
      interval: 5s
      retries: 10
      start_period: 50s
      test: rabbitmq-diagnostics check_port_connectivity
      timeout: 3s
    ports:
    - 5672:5672
    - 15672:15672
  count_0:
    build:
      context: ./
      dockerfile: count/Dockerfile
    container_name: count_0
    depends_on:
    - gateway
    environment:
    - ID=0
    - INPUT_QUEUE=count_queue
    - OUTPUT_QUEUE=results_queue
    - MOM_HOST=rabbitmq
    - PYTHONUNBUFFERED=1
    - COUNT_AMOUNT=1
    - COUNT_PREFIX=count
  filter_0:
    build:
      context: ./
      dockerfile: filter/Dockerfile
    container_name: filter_0
    depends_on:
    - count_0
    environment:
    - AGGREGATION_AMOUNT=1
    - AGGREGATION_PREFIX=aggregation
    - ID=0
    - INPUT_QUEUE=input_queue
    - OUTPUT_QUEUE=count_queue
    - MOM_HOST=rabbitmq
    - PYTHONUNBUFFERED=1
    - FILTER_AMOUNT=1
    - FILTER_PREFIX=filter
